from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.select import Select
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType
from src.testproject.sdk.drivers import webdriver
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: My first Project
    Package: TestProject.Generated.Tests.MyFirstProject
    Test: Single page signup
    Generated by: Muhammad Ibrahim (ibrahimrehman88@gmail.com)
    Generated on 07/05/2022, 12:25:13
"""


@pytest.fixture()
def driver():
    driver = webdriver.Chrome(token="f_1hwOkIkbvjwf4rvPdMFYhyyPVAHDHrICakI0LD98g",
                              project_name="My first Project",
                              job_name="Single page signup")
    step_settings = StepSettings(timeout=15000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "https://avaxdev.akru.co/register"

    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')

    # 2. Click 'firstName'
    firstname = driver.find_element(By.CSS_SELECTOR,
                                    "[name='firstName']")
    firstname.click()

    # 3. Type 'ibrahim' in 'firstName'
    firstname = driver.find_element(By.CSS_SELECTOR,
                                    "[name='firstName']")
    firstname.send_keys("ibrahim")

    # 4. Click 'lastName'
    lastname = driver.find_element(By.CSS_SELECTOR,
                                   "[name='lastName']")
    lastname.click()

    # 5. Type 'rehman' in 'lastName'
    lastname = driver.find_element(By.CSS_SELECTOR,
                                   "[name='lastName']")
    lastname.send_keys("rehman")

    # 6. Click 'email'
    email = driver.find_element(By.CSS_SELECTOR,
                                "[name='email']")
    email.click()

    # 7. Scroll window by ('0','225')
    driver.execute_script("window.scrollBy(0,225)")

    # 8. Type 'ibrahimav53@yopmail.com' in 'email'
    email = driver.find_element(By.CSS_SELECTOR,
                                "[name='email']")
    email.send_keys("ibrahimav53@yopmail.com")

    # 9. Click 'address'
    address = driver.find_element(By.CSS_SELECTOR,
                                  "[name='address']")
    address.click()

    # 10. Type 'california' in 'address'
    address = driver.find_element(By.CSS_SELECTOR,
                                  "[name='address']")
    address.send_keys("california")

    # 11. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 12. Scroll window by ('0','152')
    driver.execute_script("window.scrollBy(0,152)")

    # 13. Click 'stateName'
    statename = driver.find_element(By.CSS_SELECTOR,
                                    "[name='stateName']")
    statename.click()

    # 14. Select the 'California' option in 'stateName'
    statename = driver.find_element(By.CSS_SELECTOR,
                                    "[name='stateName']")
    Select(statename).select_by_value("California")

    # 15. Click 'city'
    city = driver.find_element(By.CSS_SELECTOR,
                               "[name='city']")
    city.click()

    # 16. Type 'california' in 'city'
    city = driver.find_element(By.CSS_SELECTOR,
                               "[name='city']")
    city.send_keys("california")

    # 17. Click 'zipCode'
    zipcode = driver.find_element(By.CSS_SELECTOR,
                                  "[name='zipCode']")
    zipcode.click()

    # 18. Type '22000' in 'zipCode'
    zipcode = driver.find_element(By.CSS_SELECTOR,
                                  "[name='zipCode']")
    zipcode.send_keys("22000")

    # 19. Click 'number'
    number = driver.find_element(By.CSS_SELECTOR,
                                 "#outlined-error-helper-text")
    number.click()

    # 20. Type '1928938922' in 'number'
    number = driver.find_element(By.CSS_SELECTOR,
                                 "#outlined-error-helper-text")
    number.send_keys("1928938922")

    # 21. Scroll window by ('0','84')
    driver.execute_script("window.scrollBy(0,84)")

    # 22. Click 'number'
    number = driver.find_element(By.CSS_SELECTOR,
                                 "#outlined-error-helper-text")
    number.click()

    # 23. Scroll window by ('0','56')
    driver.execute_script("window.scrollBy(0,56)")

    # 24. Type '7653966476' in 'number'
    number = driver.find_element(By.CSS_SELECTOR,
                                 "#outlined-error-helper-text")
    number.send_keys("7653966476")

    # 25. Click 'date-picker-dialog'
    date_picker_dialog = driver.find_element(By.CSS_SELECTOR,
                                             "#date-picker-dialog")
    date_picker_dialog.click()

    # 26. Type '14111999' in 'date-picker-dialog'
    date_picker_dialog = driver.find_element(By.CSS_SELECTOR,
                                             "#date-picker-dialog")
    date_picker_dialog.send_keys("14111999")

    # 27. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 28. Scroll window by ('0','237')
    driver.execute_script("window.scrollBy(0,237)")

    # 29. Click 'securityNumber'
    securitynumber = driver.find_element(By.CSS_SELECTOR,
                                         "[name='securityNumber']")
    securitynumber.click()

    # 30. Scroll window by ('0','276')
    driver.execute_script("window.scrollBy(0,276)")

    # 31. Type '287237622' in 'securityNumber'
    securitynumber = driver.find_element(By.CSS_SELECTOR,
                                         "[name='securityNumber']")
    securitynumber.send_keys("287237622")

    # 32. Click 'Capital appreciation'
    capital_appreciation = driver.find_element(By.CSS_SELECTOR,
                                               "#investor-purpose")
    capital_appreciation.click()

    # 33. Click 'Capital appreciation1'
    capital_appreciation1 = driver.find_element(By.XPATH,
                                                "//li/span[. = 'Capital appreciation']")
    capital_appreciation1.click()

    # 34. Scroll window by ('0','140')
    driver.execute_script("window.scrollBy(0,140)")

    # 35. Click 'No'
    no = driver.find_element(By.CSS_SELECTOR,
                             "#isTradingLowSecurities")
    no.click()

    # 36. Click 'LI'
    li = driver.find_element(By.XPATH,
                             "//li[1]")
    li.click()

    # 37. Scroll window by ('0','281')
    driver.execute_script("window.scrollBy(0,281)")

    # 38. Scroll window by ('0','221')
    driver.execute_script("window.scrollBy(0,221)")

    # 39. Click '​'
    _ = driver.find_element(By.CSS_SELECTOR,
                            "#employmentStatus")
    _.click()

    # 40. Click 'Unemployed'
    unemployed = driver.find_element(By.XPATH,
                                     "//li[. = 'Unemployed']")
    unemployed.click()

    # 41. Scroll window by ('0','191')
    driver.execute_script("window.scrollBy(0,191)")

    # 42. Scroll window by ('0','132')
    driver.execute_script("window.scrollBy(0,132)")

    # 43. Click 'I understand that there is no guarant...'
    i_understand_that_there_is_no_guarant_ = driver.find_element(By.XPATH,
                                                                 "//span[. = 'I understand that there is no guarantee of any financial returns on this investment(s) and that I run the risk of loss in my investment(s); and that I have not been provided tax advice by AKRU INC.']")
    i_understand_that_there_is_no_guarant_.click()

    # 44. Scroll window by ('0','101')
    driver.execute_script("window.scrollBy(0,101)")

    # 45. Click 'point2'
    point2 = driver.find_element(By.CSS_SELECTOR,
                                 "[name='point2']")
    point2.click()

    # 46. Click 'point3'
    point3 = driver.find_element(By.CSS_SELECTOR,
                                 "[name='point3']")
    point3.click()

    # 47. Scroll window by ('0','84')
    driver.execute_script("window.scrollBy(0,84)")

    # 48. Scroll window by ('0','33')
    driver.execute_script("window.scrollBy(0,33)")

    # 49. Scroll window by ('0','24')
    driver.execute_script("window.scrollBy(0,24)")

    # 50. Click 'point4'
    point4 = driver.find_element(By.CSS_SELECTOR,
                                 "[name='point4']")
    point4.click()

    # 51. Click 'point5'
    point5 = driver.find_element(By.CSS_SELECTOR,
                                 "[name='point5']")
    point5.click()

    # 52. Scroll window by ('0','124')
    driver.execute_script("window.scrollBy(0,124)")

    # 53. Click 'DIV'
    # Step switches frame driver context.
    driver.switch_to.default_content()
    driver.switch_to.frame(
        driver.find_element(By.XPATH,
                            "//*[@name = 'a-2v8b0mcvgkhf']|/html/body/div[1]/div/section/div/div/div/form/div[5]/div/div/div/div/div/div/div/iframe"))
    div = driver.find_element(By.XPATH,
                              "//span/div[1]")
    div.click()

    # 54. Click 'IMG'
    # Step switches frame driver context.
    driver.switch_to.default_content()
    driver.switch_to.frame(
        driver.find_element(By.XPATH,
                            "//*[@name = 'c-2v8b0mcvgkhf']|/html/body/div[2]/div[4]/iframe"))
    img = driver.find_element(By.XPATH,
                              "//tr[3]/td[1]//img")
    img.click()

    # 55. Click 'IMG1'
    # Step switches frame driver context.
    driver.switch_to.default_content()
    driver.switch_to.frame(
        driver.find_element(By.XPATH,
                            "//*[@name = 'c-2v8b0mcvgkhf']|/html/body/div[2]/div[4]/iframe"))
    img1 = driver.find_element(By.XPATH,
                               "//tr[2]/td[3]//img")
    img1.click()

    # 56. Click 'IMG2'
    # Step switches frame driver context.
    driver.switch_to.default_content()
    driver.switch_to.frame(
        driver.find_element(By.XPATH,
                            "//*[@name = 'c-2v8b0mcvgkhf']|/html/body/div[2]/div[4]/iframe"))
    img2 = driver.find_element(By.XPATH,
                               "//tr[1]/td[2]//img")
    img2.click()

    # 57. Click 'VERIFY'
    # Step switches frame driver context.
    driver.switch_to.default_content()
    driver.switch_to.frame(
        driver.find_element(By.XPATH,
                            "//*[@name = 'c-2v8b0mcvgkhf']|/html/body/div[2]/div[4]/iframe"))
    verify = driver.find_element(By.CSS_SELECTOR,
                                 "#recaptcha-verify-button")
    verify.click()

    # 58. Click 'Submit'
    submit = driver.find_element(By.XPATH,
                                 "//button[. = 'Submit']")
    submit.click()

    # 59. Scroll window by ('0','-914')
    driver.execute_script("window.scrollBy(0,-914)")

    # 60. Click 'FORM'
    form = driver.find_element(By.XPATH,
                               "//form")
    form.click()

    # 61. Scroll window by ('0','-47')
    driver.execute_script("window.scrollBy(0,-47)")

    # 62. Click 'DIV'
    # Step switches frame driver context.
    driver.switch_to.default_content()
    driver.switch_to.frame(
        driver.find_element(By.XPATH,
                            "//*[@name = 'a-2v8b0mcvgkhf']|/html/body/div[1]/div/section/div/div/div/form/div[5]/div/div/div/div/div/div/div/iframe"))
    div = driver.find_element(By.XPATH,
                              "//span/div[1]")
    div.click()

    # 63. Click 'VERIFY'
    # Step switches frame driver context.
    driver.switch_to.default_content()
    driver.switch_to.frame(
        driver.find_element(By.XPATH,
                            "//*[@name = 'c-2v8b0mcvgkhf']|/html/body/div[2]/div[4]/iframe"))
    verify = driver.find_element(By.CSS_SELECTOR,
                                 "#recaptcha-verify-button")
    verify.click()

    # 64. Click 'IMG2'
    # Step switches frame driver context.
    driver.switch_to.default_content()
    driver.switch_to.frame(
        driver.find_element(By.XPATH,
                            "//*[@name = 'c-2v8b0mcvgkhf']|/html/body/div[2]/div[4]/iframe"))
    img2 = driver.find_element(By.XPATH,
                               "//tr[1]/td[2]//img")
    img2.click()

    # 65. Click 'IMG3'
    # Step switches frame driver context.
    driver.switch_to.default_content()
    driver.switch_to.frame(
        driver.find_element(By.XPATH,
                            "//*[@name = 'c-2v8b0mcvgkhf']|/html/body/div[2]/div[4]/iframe"))
    img3 = driver.find_element(By.XPATH,
                               "//tr[1]/td[1]//img")
    img3.click()

    # 66. Click 'IMG1'
    # Step switches frame driver context.
    driver.switch_to.default_content()
    driver.switch_to.frame(
        driver.find_element(By.XPATH,
                            "//*[@name = 'c-2v8b0mcvgkhf']|/html/body/div[2]/div[4]/iframe"))
    img1 = driver.find_element(By.XPATH,
                               "//tr[2]/td[3]//img")
    img1.click()

    # 67. Click 'VERIFY'
    # Step switches frame driver context.
    driver.switch_to.default_content()
    driver.switch_to.frame(
        driver.find_element(By.XPATH,
                            "//*[@name = 'c-2v8b0mcvgkhf']|/html/body/div[2]/div[4]/iframe"))
    verify = driver.find_element(By.CSS_SELECTOR,
                                 "#recaptcha-verify-button")
    verify.click()

    # 68. Click 'Submit'
    submit = driver.find_element(By.XPATH,
                                 "//button[. = 'Submit']")
    submit.click()

    # 69. Click 'v1'
    v1 = driver.find_element(By.CSS_SELECTOR,
                             "#v1")
    v1.click()

    # 70. Type '0' in 'v1'
    v1 = driver.find_element(By.CSS_SELECTOR,
                             "#v1")
    v1.send_keys("0")

    # 71. Type '0' in 'v2'
    v2 = driver.find_element(By.CSS_SELECTOR,
                             "#v2")
    v2.send_keys("0")

    # 72. Type '0' in 'v3'
    v3 = driver.find_element(By.CSS_SELECTOR,
                             "#v3")
    v3.send_keys("0")

    # 73. Type '0' in 'v4'
    v4 = driver.find_element(By.CSS_SELECTOR,
                             "#v4")
    v4.send_keys("0")

    # 74. Type '8' in 'v5'
    v5 = driver.find_element(By.CSS_SELECTOR,
                             "#v5")
    v5.send_keys("8")

    # 75. Type '8' in 'v6'
    v6 = driver.find_element(By.CSS_SELECTOR,
                             "#v6")
    v6.send_keys("8")

    # 76. Type '8' in 'v7'
    v7 = driver.find_element(By.CSS_SELECTOR,
                             "#v7")
    v7.send_keys("8")

    # 77. Type '8' in 'v8'
    v8 = driver.find_element(By.CSS_SELECTOR,
                             "#v8")
    v8.send_keys("8")

    # 78. Click 'Verify OTP'
    verify_otp = driver.find_element(By.XPATH,
                                     "//button[. = 'Verify OTP']")
    verify_otp.click()
